import { useState } from "react";
import { ArrowLeft, Printer, FileText, CheckCircle2, ChevronDown, ChevronUp, Clock, FileSearch, BarChart2 } from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";
import { Badge, StatusDot } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { getCompany, getRisks, getDocuments, type ReportItem } from "@/lib/mockData";
import { Reveal } from "@/components/layout/PageHeader";
import { motion, AnimatePresence } from "framer-motion";
import { ConfidenceRing } from "@/components/ui/ConfidenceRing";
import { cn } from "@/lib/utils";

interface InvestmentMemoViewProps {
  report: ReportItem;
  onBack: () => void;
}

export function InvestmentMemoView({ report, onBack }: InvestmentMemoViewProps) {
  const company = getCompany(report.companyId);
  const risks = getRisks(report.companyId);
  const documents = getDocuments(report.companyId);
  const [expandedRisks, setExpandedRisks] = useState<Record<string, boolean>>({});
  const [selectedCitation, setSelectedCitation] = useState<string | null>(null);

  if (!company) return null;

  // Derive scores deterministically from existing mock data
  const riskComponent = 100 - company.riskScore;
  const financialsComponent = Math.min(100, Math.round(company.irr * 3 + 10));
  const growthComponent = Math.min(100, Math.round(company.moic * 30));
  const marketComponent = 84; // Static deterministic value
  const confidence = 91; 
  
  const totalScore = Math.round((riskComponent + financialsComponent + growthComponent + marketComponent) / 4);
  const recommendation = totalScore > 80 ? "BUY" : totalScore > 60 ? "HOLD" : "REJECT";
  const expectedReturn = company.irr > 20 ? "High" : company.irr > 10 ? "Medium" : "Low";
  const riskLevel = company.riskScore > 60 ? "High" : company.riskScore > 30 ? "Medium" : "Low";

  const toggleRisk = (id: string) => {
    setExpandedRisks(prev => ({ ...prev, [id]: !prev[id] }));
  };

  return (
    <div className="mx-auto max-w-[1400px] pb-16 pt-6">
      {/* Action Bar */}
      <div className="flex items-center justify-between px-8 mb-6 print:hidden">
        <button
          onClick={onBack}
          className="flex items-center gap-2 text-sm text-[var(--color-ink-3)] hover:text-[var(--color-ink-1)] transition-colors focus:outline-none"
        >
          <ArrowLeft size={16} /> Back to Reports
        </button>
        <Button variant="secondary" size="sm" onClick={() => window.print()}>
          <Printer size={14} /> Print Memo
        </Button>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[1fr_320px] gap-6 px-8 items-start">
        
        {/* Main Memo Content */}
        <div className="space-y-8 min-w-0 print:w-full">
          
          {/* Header & Meta */}
          <Reveal delay={0}>
            <div>
              <div className="flex items-center gap-3 mb-3">
                <Badge tone="emerald">{report.type}</Badge>
                <Badge tone={report.status === "final" ? "emerald" : "amber"}>{report.status.toUpperCase()}</Badge>
              </div>
              <h1 className="font-display text-3xl text-[var(--color-ink-0)] leading-tight mb-4">{report.title}</h1>
              
              <div className="flex flex-wrap gap-x-8 gap-y-3 py-4 border-y border-[var(--color-border-hairline)] bg-white/[0.01]">
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Generated By</p>
                  <p className="text-[13px] text-[var(--color-ink-1)] font-medium">DealOS AI</p>
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Analyst</p>
                  <p className="text-[13px] text-[var(--color-ink-1)] font-medium">AI Investment Analyst</p>
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Generated</p>
                  <p className="text-[13px] text-[var(--color-ink-1)] font-mono">{report.date}</p>
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Documents Analysed</p>
                  <p className="text-[13px] text-[var(--color-ink-1)] font-mono">{documents.length}</p>
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Model</p>
                  <p className="text-[13px] text-[var(--color-ink-1)] font-mono">GPT-4o</p>
                </div>
                <div>
                  <p className="text-[10px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Processing Time</p>
                  <p className="text-[13px] text-[var(--color-ink-1)] font-mono">18.2 sec</p>
                </div>
              </div>
            </div>
          </Reveal>

          {/* Investment Decision Panel */}
          <Reveal delay={0.05}>
            <GlassCard className="p-6 border border-[var(--color-gold-500)]/20 shadow-[0_8px_32px_-12px_rgba(201,162,39,0.12)]">
              <div className="flex flex-col md:flex-row gap-8 items-center md:items-stretch">
                
                <div className="flex-1 w-full space-y-4">
                  <div className="flex items-center justify-between">
                    <p className="font-display text-sm text-[var(--color-ink-3)] uppercase tracking-wider">Investment Decision</p>
                    <div className="flex items-center gap-2">
                      <ConfidenceRing value={confidence} size={20} />
                      <span className="text-xs text-[var(--color-ink-2)] font-mono">{confidence}% Confidence</span>
                    </div>
                  </div>
                  
                  <div className="flex items-end gap-4">
                    <h2 className={cn(
                      "font-display text-5xl tracking-tight leading-none",
                      recommendation === "BUY" ? "text-[var(--color-emerald)]" : recommendation === "HOLD" ? "text-[var(--color-amber)]" : "text-[var(--color-crimson)]"
                    )}>
                      {recommendation}
                    </h2>
                    <div className="flex gap-1 mb-1">
                      {Array.from({ length: 10 }).map((_, i) => (
                        <div key={i} className={cn("h-6 w-2 rounded-sm", i < Math.round(totalScore/10) ? (recommendation === "BUY" ? "bg-[var(--color-emerald)]" : "bg-[var(--color-amber)]") : "bg-white/10")} />
                      ))}
                    </div>
                  </div>

                  <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-4 border-t border-[var(--color-border-hairline)]">
                    <div>
                      <p className="text-[11px] text-[var(--color-ink-4)] uppercase tracking-wide mb-1">Inv. Score</p>
                      <p className="text-lg font-mono text-[var(--color-ink-0)]">{totalScore}</p>
                    </div>
                    <div>
                      <p className="text-[11px] text-[var(--color-ink-4)] uppercase tracking-wide mb-1">Exp. Return</p>
                      <p className="text-lg text-[var(--color-ink-0)]">{expectedReturn}</p>
                    </div>
                    <div>
                      <p className="text-[11px] text-[var(--color-ink-4)] uppercase tracking-wide mb-1">Risk Level</p>
                      <p className="text-lg text-[var(--color-ink-0)]">{riskLevel}</p>
                    </div>
                    <div>
                      <p className="text-[11px] text-[var(--color-ink-4)] uppercase tracking-wide mb-1">Horizon</p>
                      <p className="text-lg text-[var(--color-ink-0)]">3-5 Years</p>
                    </div>
                  </div>
                </div>

                <div className="hidden md:block w-px bg-[var(--color-border-hairline)]" />

                <div className="w-full md:w-48 shrink-0 space-y-3">
                  <p className="text-xs font-medium text-[var(--color-ink-2)] mb-4">Score Breakdown</p>
                  {[
                    { label: "Financials", score: financialsComponent },
                    { label: "Risk Profile", score: riskComponent },
                    { label: "Growth", score: growthComponent },
                    { label: "Market Pos", score: marketComponent }
                  ].map(item => (
                    <div key={item.label} className="space-y-1.5">
                      <div className="flex justify-between text-[11px]">
                        <span className="text-[var(--color-ink-3)]">{item.label}</span>
                        <span className="font-mono text-[var(--color-ink-1)]">{item.score}</span>
                      </div>
                      <div className="h-1 w-full bg-white/5 rounded-full overflow-hidden">
                        <div className="h-full bg-[var(--color-gold-400)] rounded-full" style={{ width: `${item.score}%` }} />
                      </div>
                    </div>
                  ))}
                </div>

              </div>
            </GlassCard>
          </Reveal>

          {/* AI Reasoning Checklist */}
          <Reveal delay={0.1}>
            <div className="space-y-4 break-inside-avoid">
              <h3 className="font-display text-lg text-[var(--color-ink-0)] border-b border-[var(--color-border-hairline)] pb-2">AI Reasoning Summary</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="flex items-start gap-3 bg-[var(--color-emerald)]/[0.05] border border-[var(--color-emerald)]/10 p-3 rounded-lg">
                  <CheckCircle2 size={16} className="text-[var(--color-emerald)] mt-0.5 shrink-0" />
                  <p className="text-[13px] text-[var(--color-ink-1)] leading-relaxed">
                    Strong historical revenue growth evidenced in recent filings.
                  </p>
                </div>
                <div className="flex items-start gap-3 bg-[var(--color-emerald)]/[0.05] border border-[var(--color-emerald)]/10 p-3 rounded-lg">
                  <CheckCircle2 size={16} className="text-[var(--color-emerald)] mt-0.5 shrink-0" />
                  <p className="text-[13px] text-[var(--color-ink-1)] leading-relaxed">
                    Healthy gross margin profile aligned with top-quartile sector benchmarks.
                  </p>
                </div>
                <div className="flex items-start gap-3 bg-[var(--color-emerald)]/[0.05] border border-[var(--color-emerald)]/10 p-3 rounded-lg">
                  <CheckCircle2 size={16} className="text-[var(--color-emerald)] mt-0.5 shrink-0" />
                  <p className="text-[13px] text-[var(--color-ink-1)] leading-relaxed">
                    Proven ability to execute add-on acquisitions and integrate efficiently.
                  </p>
                </div>
                <div className="flex items-start gap-3 bg-[var(--color-emerald)]/[0.05] border border-[var(--color-emerald)]/10 p-3 rounded-lg">
                  <CheckCircle2 size={16} className="text-[var(--color-emerald)] mt-0.5 shrink-0" />
                  <p className="text-[13px] text-[var(--color-ink-1)] leading-relaxed">
                    Low leverage profile provides headroom for further inorganic growth.
                  </p>
                </div>
              </div>
            </div>
          </Reveal>

          {/* Executive Summary */}
          <Reveal delay={0.15}>
            <div className="space-y-4 break-inside-avoid">
              <h3 className="font-display text-lg text-[var(--color-ink-0)] border-b border-[var(--color-border-hairline)] pb-2">Executive Summary</h3>
              <div className="text-sm text-[var(--color-ink-2)] leading-loose space-y-4">
                <p>
                  {company.name} ({company.ticker}) represents a compelling investment opportunity within the {company.sector} sector, primarily focused on {company.geography}. The company has demonstrated a robust financial trajectory, scaling to a deal value of ${(company.dealValue / 1000000).toFixed(0)}M while maintaining disciplined capital allocation. 
                </p>
                <p>
                  {company.description} The underlying unit economics remain highly attractive, supported by a scalable infrastructure and a defensible market position. With an underwritten IRR of {company.irr}% and a MOIC of {company.moic}x, the asset aligns closely with the flagship fund's return thresholds.
                </p>
                <p>
                  While certain operational risks have been identified through diligence, mitigants are present or readily implementable post-close. The recommendation is to proceed with confirmatory diligence and finalize the term sheet structure.
                </p>
              </div>
            </div>
          </Reveal>

          {/* Financial Highlights */}
          <Reveal delay={0.2}>
            <div className="space-y-4 break-inside-avoid">
              <h3 className="font-display text-lg text-[var(--color-ink-0)] border-b border-[var(--color-border-hairline)] pb-2">Financial Highlights</h3>
              {company.history && company.history.length > 0 ? (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                  {company.history.slice(-1).map(latest => {
                    const prev = company.history[company.history.length - 2];
                    const revenueGrowth = prev ? ((latest.revenue - prev.revenue) / prev.revenue) * 100 : 0;
                    const ebitdaMargin = (latest.ebitda / latest.revenue) * 100;
                    const prevEbitdaMargin = prev ? (prev.ebitda / prev.revenue) * 100 : 0;
                    const marginGrowth = ebitdaMargin - prevEbitdaMargin;

                    return (
                      <div key="kpis" className="col-span-full grid grid-cols-2 md:grid-cols-4 gap-4">
                        <GlassCard className="p-4" raised>
                          <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Revenue ({latest.period})</p>
                          <div className="flex items-end gap-2">
                            <p className="text-2xl font-mono text-[var(--color-ink-0)]">${latest.revenue}M</p>
                            {prev && (
                              <span className={cn("text-xs font-mono mb-1", revenueGrowth >= 0 ? "text-[var(--color-emerald)]" : "text-[var(--color-crimson)]")}>
                                {revenueGrowth >= 0 ? "+" : ""}{revenueGrowth.toFixed(1)}%
                              </span>
                            )}
                          </div>
                        </GlassCard>
                        <GlassCard className="p-4" raised>
                          <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">EBITDA ({latest.period})</p>
                          <div className="flex items-end gap-2">
                            <p className="text-2xl font-mono text-[var(--color-ink-0)]">${latest.ebitda}M</p>
                          </div>
                        </GlassCard>
                        <GlassCard className="p-4" raised>
                          <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">EBITDA Margin</p>
                          <div className="flex items-end gap-2">
                            <p className="text-2xl font-mono text-[var(--color-ink-0)]">{ebitdaMargin.toFixed(1)}%</p>
                            {prev && (
                              <span className={cn("text-xs font-mono mb-1", marginGrowth >= 0 ? "text-[var(--color-emerald)]" : "text-[var(--color-crimson)]")}>
                                {marginGrowth >= 0 ? "+" : ""}{marginGrowth.toFixed(1)}bps
                              </span>
                            )}
                          </div>
                        </GlassCard>
                        <GlassCard className="p-4" raised>
                          <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1">Net Income</p>
                          <div className="flex items-end gap-2">
                            <p className="text-2xl font-mono text-[var(--color-ink-0)]">${latest.netIncome}M</p>
                          </div>
                        </GlassCard>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="p-6 border border-dashed border-[var(--color-border-strong)] rounded-lg text-center">
                  <p className="text-sm text-[var(--color-ink-4)]">Financial metrics Not Available</p>
                </div>
              )}
            </div>
          </Reveal>

          {/* Risk Assessment */}
          <Reveal delay={0.25}>
            <div className="space-y-4 break-inside-avoid">
              <h3 className="font-display text-lg text-[var(--color-ink-0)] border-b border-[var(--color-border-hairline)] pb-2">Risk Assessment</h3>
              {risks.length > 0 ? (
                <div className="space-y-3">
                  {risks.map((risk) => (
                    <GlassCard key={risk.id} className="overflow-hidden" raised>
                      <button
                        onClick={() => toggleRisk(risk.id)}
                        className="w-full flex items-center justify-between p-4 hover:bg-white/[0.02] transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-gold-500)]"
                      >
                        <div className="flex items-center gap-4">
                          <StatusDot tone={risk.severity === "critical" || risk.severity === "high" ? "crimson" : risk.severity === "medium" ? "amber" : "ice"} />
                          <p className="text-[13.5px] font-medium text-[var(--color-ink-1)] text-left">{risk.title}</p>
                        </div>
                        <div className="flex items-center gap-4">
                          <Badge tone="neutral">{risk.category}</Badge>
                          {expandedRisks[risk.id] ? <ChevronUp size={16} className="text-[var(--color-ink-4)]" /> : <ChevronDown size={16} className="text-[var(--color-ink-4)]" />}
                        </div>
                      </button>
                      <AnimatePresence>
                        {expandedRisks[risk.id] && (
                          <motion.div
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: "auto", opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            transition={{ duration: 0.2 }}
                            className="border-t border-[var(--color-border-hairline)] bg-white/[0.01]"
                          >
                            <div className="p-4 space-y-4">
                              <div>
                                <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1.5">Description</p>
                                <p className="text-sm text-[var(--color-ink-2)] leading-relaxed">{risk.summary}</p>
                              </div>
                              <div className="grid grid-cols-2 gap-4">
                                <div>
                                  <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1.5">Impact</p>
                                  <p className="text-[13px] text-[var(--color-ink-2)]">Potential margin compression if unmitigated. Requires legal review.</p>
                                </div>
                                <div>
                                  <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-1.5">Recommendation</p>
                                  <p className="text-[13px] text-[var(--color-ink-2)]">Structure contingent consideration or indemnification clause.</p>
                                </div>
                              </div>
                              <div className="pt-3 border-t border-[var(--color-border-hairline)] flex items-center justify-between">
                                <p className="text-xs text-[var(--color-ink-4)] flex items-center gap-1.5">
                                  <FileSearch size={12} /> Found in {risk.source}, Page {risk.page}
                                </p>
                                <Button 
                                  variant="ghost" 
                                  size="sm" 
                                  className="h-7 text-xs" 
                                  onClick={() => setSelectedCitation(`risk-${risk.id}`)}
                                >
                                  View Evidence
                                </Button>
                              </div>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </GlassCard>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-[var(--color-ink-3)]">No risks detected for this entity.</p>
              )}
            </div>
          </Reveal>

        </div>

        {/* Sticky Sidebar: Timeline & Evidence */}
        <div className="space-y-6 sticky top-24 print:hidden">
          
          {/* Processing Timeline */}
          <GlassCard className="p-5" raised>
            <p className="font-display text-[15px] text-[var(--color-ink-0)] mb-5 flex items-center gap-2">
              <Clock size={16} className="text-[var(--color-gold-400)]" /> Processing Timeline
            </p>
            <div className="space-y-4 relative before:absolute before:inset-0 before:ml-[9px] before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-[var(--color-border-hairline)] before:z-0">
              {[
                { label: "Data Room Ingested", time: documents.length > 0 ? documents[0].uploaded : "N/A" },
                { label: "Metrics Extracted", time: "Analysis Complete" },
                { label: "Risks Flagged", time: `${risks.length} Detected` },
                { label: "Memo Generated", time: report.date }
              ].map((step, i) => (
                <div key={i} className="relative z-10 flex items-center gap-3">
                  <div className="h-5 w-5 rounded-full bg-[var(--color-surface-0)] border-2 border-[var(--color-gold-500)] flex items-center justify-center shrink-0">
                    <div className="h-1.5 w-1.5 bg-[var(--color-gold-400)] rounded-full" />
                  </div>
                  <div>
                    <p className="text-[12px] font-medium text-[var(--color-ink-1)] leading-none">{step.label}</p>
                    <p className="text-[10px] text-[var(--color-ink-4)] font-mono mt-1">{step.time}</p>
                  </div>
                </div>
              ))}
            </div>
          </GlassCard>

          {/* Evidence Panel */}
          <GlassCard className="p-5" raised>
            <div className="flex items-center justify-between mb-4">
              <p className="font-display text-[15px] text-[var(--color-ink-0)] flex items-center gap-2">
                <FileSearch size={16} className="text-[var(--color-gold-400)]" /> Evidence Panel
              </p>
              <Badge tone="neutral">{documents.length} Citations</Badge>
            </div>
            
            <div className="space-y-3">
              <p className="text-[11px] uppercase tracking-wider text-[var(--color-ink-4)] mb-2">Selected References</p>
              {documents.slice(0, 3).map((doc, i) => (
                <button
                  key={doc.id}
                  onClick={() => setSelectedCitation(doc.id)}
                  className={cn(
                    "w-full text-left p-3 rounded-lg border transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-gold-500)]",
                    selectedCitation === doc.id
                      ? "bg-[var(--color-gold-500)]/[0.05] border-[var(--color-gold-500)]/30"
                      : "bg-white/[0.01] border-[var(--color-border-hairline)] hover:border-[var(--color-border-strong)] hover:bg-white/[0.03]"
                  )}
                >
                  <p className="text-[12.5px] font-medium text-[var(--color-ink-1)] truncate mb-1">{doc.name}</p>
                  <div className="flex items-center justify-between text-[11px] text-[var(--color-ink-4)] font-mono">
                    <span>Page {Math.floor(Math.random() * doc.pages) + 1}</span>
                    <span className="flex items-center gap-1"><ConfidenceRing value={doc.confidence || 95} size={12} /> {doc.confidence || 95}%</span>
                  </div>
                  <AnimatePresence>
                    {selectedCitation === doc.id && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        className="overflow-hidden"
                      >
                        <div className="mt-2 pt-2 border-t border-[var(--color-gold-500)]/20">
                          <p className="text-[11px] text-[var(--color-ink-2)] italic leading-relaxed bg-[var(--color-gold-500)]/[0.05] px-2 py-1.5 rounded text-justify">
                            "...we expect the synergies realized from the recent acquisition to substantially offset the anticipated margin compression in Q4."
                          </p>
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </button>
              ))}
              <Button variant="ghost" size="sm" className="w-full justify-center text-xs mt-2">
                View all citations
              </Button>
            </div>
          </GlassCard>

        </div>
      </div>
    </div>
  );
}
